project: 'diffusion'
program: goal_prox/main.py
method: grid

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "diff-only"
  alg:
    value: "diff-bc"
  traj-load-path:
    value: "./expert_datasets/hand_v2.pt"
  ddpm-path:
    value: "./rl-toolkit/dm/hand_v2_ddpm.pt"
  env-name:
    value: "CustomHandManipulateBlockRotateZ-v2"
  coeff:
    value: 1
  coeff-bc:
    value: 0
  normalize-env:
    value: False
  bc-num-epochs:
    value: 5000
  eval-num-processes:
    value: 1
  cuda:
    value: True
  num-render:
    value: 1
  num-eval:
    value: 100
  vid-fps:
    value: 100
  lr:
    value: 0.00005
  log-interval:
    value: 500
  save-interval:
    value: 10000
  eval-interval:
    value: 500
  bc-state-norm:
    value: True
  clip-actions:
    value: True
