project: 'diffusion'
program: goal_prox/main.py
method: grid

parameters:
  seed:
    # values: [1, 2, 3]
    value: 1
  prefix:
    value: "sac"
  alg:
    value: "sac"
  env-name:
    value: "CustomHandManipulateBlockRotateZ-v0"
  normalize-env:
    value: False
  eval-num-processes:
    value: 1
  num-processes:
    value: 8
  num-render:
    value: 1
  num-eval:
    value: 100
  lr:
    values: [0.00005, 0.0001, 0.0002, 0.0005]
  critic-lr:
    values: [0.00005]
  log-interval:
    value: 1000
  save-interval:
    value: 100000
  eval-interval:
    value: 5000
  clip-actions:
    value: True
  num-env-steps:
    value: 8000000
