project: 'diffusion'
program: goal_prox/main.py
method: grid

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "diff-bc"
  alg:
    value: "diff-bc"
  traj-load-path:
    value: "./expert_datasets/pick_10000_clip.pt"
  ddpm-path:
    value: "./rl-toolkit/dm/pick_10000_clip_norm_ddpm.pt"
  env-name:
    value: "FetchPickAndPlaceDiffHoldout-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 4000
  eval-num-processes:
    value: 1
  coeff:
    value: 1
    #value: 0.1
  coeff-bc:
    value: 0
  cuda:
    value: True
  num-render:
    value: 1
  num-eval:
    value: 100
  #vid-fps:
    #value: 100
  lr:
    values: [0.000002]
  log-interval:
    value: 2000
  save-interval:
    value: 100000
  eval-interval:
    value: 2000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
