project: 'diffusion'
program: goal_prox/main.py
method: grid

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "bc"
  alg:
    value: "bc"
  traj-load-path:
    value: "./expert_datasets/push_noisy_001.pt"
  env-name:
    value: "FetchPushEnvCustom-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 4000
  eval-num-processes:
    value: 1
  cuda:
    value: True
  num-render:
    value: 1
  num-eval:
    value: 100
  vid-fps:
    value: 100
  lr:
    value: 0.000001
  log-interval:
    value: 2000
  save-interval:
    value: 100000
  eval-interval:
    value: 4000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
