project: 'diffusion'
program: goal_prox/main.py
method: grid

parameters:
  seed:
    #values: [1, 2, 3]
    value: 1
  prefix:
    value: "ibc"
  alg:
    value: "ibc"
  traj-load-path:
    value: "./expert_datasets/push_10000_clip.pt"
  env-name:
    value: "FetchPushEnvCustom-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 5000
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-process:
    value: 10
  num-render:
    value: 0
  #vid-fps:
    #value: 30
  num-eval:
    value: 10
  lr:
    #values: [0.000002, 0.000005]
    value: 0.000001
  log-interval:
    value: 1000
  save-interval:
    value: 50000
  eval-interval:
    value: 2000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
  stochastic-optimizer-train_samples:
    value: 256
  traj-batch-size:
    value: 512
  hidden-dim:
    values: [256, 512, 1024]
  depth:
    values: [1, 2]
  max-grad-norm:
    value: -1
