project: 'diffusion'
program: goal_prox/main.py
method: grid

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "diff-policy"
  alg:
    value: "diff-policy"
  traj-load-path:
    value: "./expert_datasets/push_10000_clip.pt"
  env-name:
    value: "FetchPushEnvCustom-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 15000
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-render:
    value: 0
  vid-fps:
    value: 30
  num-eval:
    value: 10
  lr:
    value: 0.000002
  log-interval:
    value: 3000
  save-interval:
    value: 500000
  eval-interval:
    value: 9000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
  traj-batch-size:
    value: 128
