project: 'diffusion'
program: goal_prox/main.py
method: grid

parameters:
  seed:
    values: [1, 2, 3]
  prefix:
    value: "ae-bc"
  alg:
    value: "ae-bc"
  traj-load-path:
    value: "./expert_datasets/walker_clip_3traj_processed.pt"
  ae-path:
    value: "./rl-toolkit/rlf/algos/il/density/vae/walker_clip_3traj_processed_vae.pt"
  env-name:
    value: "Walker2d-v3"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 3000
  eval-num-processes:
    value: 1
  cuda:
    value: True
  num-render:
    value: 1
  num-eval:
    value: 100
  vid-fps:
    value: 100
  lr:
    value: 0.0001
  log-interval:
    value: 1000
  save-interval:
    value: 100000
  eval-interval:
    value: 1000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
  coeff:
    value: 0.1
